# Generated by Django 3.2.5 on 2021-12-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='is_mvp',
            new_name='is_seller_of_the_month',
        ),
    ]
